server:
  port: 8089

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:6432/statistics
    username: postgres
    password: postgres

  flyway:
    password: postgres
    user: postgres
    url: jdbc:postgresql://localhost:6432/statistics
